### ISSUE TITLE
Java API

### ISSUE THREAD

**Issue by Izocel** [Sytm/waypoints2#105]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Hi :) i'm a plugin developper myself, and I'm into "questing" programation right now.
You plugin would be usefull for quest traking etc....
Is there an API that I could implement to work with your plugin ?

Thnaks in advance 
~Izo

**Comment by Sytm** [comment]
If you just want the pointers, they are available as a separate library:
https://github.com/Sytm/waypoints/blob/v4/master/pointers/README.md

**Comment by Izocel** [comment]
Oks thanks for that can you send a list of available API from your repos such as the pointer one ?

**Comment by Sytm** [comment]
If you want to see an example on how to only use the pointers library take a look at this project: https://github.com/Sytm/quest-pointers

It might be written in Kotlin, but the usage would be the same. You just need to make sure you are additionally shading the kotlin stdlib

**Comment by Izocel** [comment]
I would be ok for how to use it i'mjust wondering if there's any other part i could use a API than pointers ?

**Comment by Sytm** [comment]
There is also an API for Waypoints itself which resides inside the waypoints-api folder/submodule, but that requires the usage of Kotlin. (I once included a hacky way to access the Kotlin api from Java, but it was really bad)

**Comment by Izocel** [comment]
Ok i feel you :P thanks for the responses -> 200 Ok : out

**Comment by Izocel** [comment]
would you have a pom.xml 'maven' example how i could import those:
Since they are in kotlin

```xml
        <repository>
            <id>md5lukas-repo-releases</id>
            <name>Md5Lukas' Reposilite Repository</name>
            <url>https://repo.md5lukas.de/releases</url>
        </repository>

        <dependency>
            <groupId>de.md5lukas.waypoints</groupId>
            <artifactId>pointers</artifactId>
            <version>4.2.0</version>
        </dependency>
        <dependency>
            <groupId>de.md5lukas.waypoints</groupId>
            <artifactId>waypoints-api</artifactId>
            <version>4.2.0</version>
        </dependency>

```

**Comment by Sytm** [comment]
You a re basically on the right track with that pom. Although `4.3.0` added functions to the waypoints-api that converts the Kotlin only suspend function into Java CompletableFutures. Kotlin code can be called from Java just fine.

Also perhaps take a look at [this](https://github.com/Sytm/waypoints/blob/v4.3.0/waypoints-api/example/src/main/java/de/md5lukas/examplej/ExamplePlugin.java) to get started
