### ISSUE TITLE
Plugin tries measuring distance between overworld and nether

### ISSUE THREAD

**Issue by hir0xygen** [Sytm/waypoints2#106]
**Describe the bug**
The plugin tries to measure the distance between a point in the overworld and a point in the nether when a waypoint in either is selected while the player is in the other.

**To Reproduce**
1. Be in the overworld or nether.
2. Select a waypoint for navigation that is in the world you're not in.
3. Look at the console.

**Expected behavior**
The plugin should not attempt this calculation and handle it properly, instead of spamming the console with repeated error messages, as seen in screenshot.

**Screenshots**
![Image depicting console output of the bug happening](https://i.imgur.com/BDxDBLE.jpg)

**Additional context**

- [x] I am using the latest version of Waypoints available

**Comment by Darr3n2GG** [comment]
Bug still exists in version 4.4.1.
https://mclo.gs/9DlC9X6#L270
