### ISSUE TITLE
Error occurred while enabling Waypoints

### ISSUE THREAD

**Issue by Forchedon** [Sytm/waypoints2#107]
**Describe the bug**
Waypoints v4.4.1 failed to enable due to an error. (Refer to screenshot below)

**To Reproduce**
After updating the plugin's version to its latest version, I went and opened the server.

**Expected behavior**
The plugin to enable without any issues.

**Screenshots**
![Screenshot_11](https://github.com/Sytm/waypoints/assets/155866957/1f6997a0-10ac-4f14-afad-f30979393d84)

**Additional context**
- [ ] I am using the latest version of Waypoints available

**Comment by Sytm** [comment]
In case you updated from v3 to v4, some config values and paths have changed. Either try deleting the config.yml file or go into the config at the path "pointers.bossBar.barStyle" and change the value to "progress" (the new name of the default value)
