### ISSUE TITLE
Displays should only work if the player is in possession of a compass

### ISSUE THREAD

**Issue by thegamerx1** [Sytm/waypoints2#11]
also option for right click while holding compass opens waypoint menu

**Comment by Sytm** [comment]
Ok, now I gotta ask. Could you be more specific about "Make it only work if user is holding a compass in hand or offhand"? Like, the compass display should only work then, or you only get the displays when you are holding a compass?

**Comment by thegamerx1** [comment]
i prefer having to hold it in hand but a option to also enable it when its in hotbar or inventory is also ok

**Comment by Sytm** [comment]
So basically the plugin only works if you have a compass in the Hotbar / hand.

**Comment by thegamerx1** [comment]
Yea having a option on config to make it only work if compass is on one of these: hotbar, hand/offhand and inventory

**Comment by thegamerx1** [comment]
or also implementing it on permissions so vips dont need to hold the compass
