### ISSUE TITLE
Inventory items lost using anvil GUI

### ISSUE THREAD

**Issue by Erlebsyk** [Sytm/waypoints2#12]
**Description**
I've noticed a bug where inventory items are permanently lost if the anvil GUI is not used correctly. If any item is shift-cliked while using the anvil GUI, the item is inserted into the second slot and can no longer be returned to the player. Example [video](https://youtu.be/N4xyhTjvHqc).

**Impact**
This is not an issue with normal use, however it can be very unfortunate if valuable items are lost if someone accidentally shift-clicks one of their items.

**Steps to reproduce**
Open GUI, add new waypoint or folder to open anvil GUI, then shift-click an item within the inventory to insert it into the second anvil slot. It is also possible to insert an item into the second anvil slot by repeatedly left-clicking it with a selected item. The inserted item is then lost.

**System**
Java 1.8
Minecraft version 1.15.2
Paper latest version (for now anyway): Paper-121 (API version 1.15.2-R0.1-SNAPSHOT)
Plugin version: 2.6.1

**Error logs**
No logs or errors displayed in console.

**Comment by Sytm** [comment]
You should report that bug to [WesJD/AnvilGUI](https://github.com/WesJD/AnvilGUI), as it is his library I am using for the anvil GUI, so sorry I cannot help you with that.

But thanks for contributing to properly formatted issues!

**Comment by Erlebsyk** [comment]
Thanks for the quick reply. This bug just got fixed in WesJD/AnvilGUI #62. See the [issue](https://github.com/WesJD/AnvilGUI/issues/70) referenced above for more details, where WesJD replied: "I appreciate the detailed issue. This issue will be fixed in #62. Please remind the plugin developer to update the plugin once I merge that PR in a few minutes.".
