### ISSUE TITLE
Doesnt work in nether

### ISSUE THREAD

**Issue by thegamerx1** [Sytm/waypoints2#16]
the compass goes crazy
![image](https://gamepedia.cursecdn.com/minecraft_gamepedia/thumb/1/1c/Compass.gif/120px-Compass.gif?version=899d8487bc39ebb1dedd482fa6427a9d)

**Comment by Sytm** [comment]
After looking around on the internet, it looks like you cannot modify this behavior with Spigot directly. You would need to change the biome the player is in from `minecraft:nether` to something else and when he leaves the chunk change it back. But I will not do this, as it messes up colors and stuff. Also when the server crashes, the biome that was previously there will be lost
