### ISSUE TITLE
Public folders for better orientation

### ISSUE THREAD

**Issue by JokaJukka** [Sytm/waypoints2#38]
I'll be running a city roleplay-like server with usage of waypoints, they are great for quick orientation in town. However, it would be great if there could be public folders (just like private ones) - this would greatly improve readability if there are many public waypoints.

Thanks for reply!

**Comment by Sytm** [comment]
I am gonna put this up for the 3.0.0 update. Can't give any date on the release yet, but this feature should be present

**Comment by Sytm** [comment]
Has been added in 3.0.0 recode
