### ISSUE TITLE
Plugin fails to load on server startup

### ISSUE THREAD

**Issue by Apeiros-46B** [Sytm/waypoints2#47]
**Describe the bug:**
The plugin does not load on server startup, thus being unusable.

**To Reproduce:**
1. Start the server using this command in the terminal inside the server directory (change RAM amount if you need to):
> java -Xms16G -Xmx16G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=20 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar purpurclip-1.16.5-1081.jar nogui
2. Look carefully at the console for this error (image is under screenshots section)

**Expected behavior:**
The plugin loads normally on server startup.

**Screenshots:**
<img width="1052" alt="Screen Shot 2021-05-15 at 6 15 39 PM" src="https://user-images.githubusercontent.com/61390942/118382377-8fb47180-b5a9-11eb-8429-7a7ffcaf868c.png">

**Server environment:**
- OS: Pop OS 20.10 (an Ubuntu derivative)
- Java Version: AdoptOpenJDK 11.0.11 w/ Hotspot VM

- Server version: Purpur 1.16.5 build 1081
- Plugin version: 2.92 (from the spigot page)
- Dependency version: 1.2-SNAPSHOT (from the spigot page)

- Plugin list:
> Plugins (43): AngelChest, AureliumSkills, BetterInvisibility*, BetterSleeping3, ChatFilter, ContainerPassthrough, CoreProtect, DiscordSRV, DynaTech, EconomyShopGUI, ElectricSpawners, Emoji*, Essentials, ExoticGarden, ExtraGear, FoxyMachines, GeneticChickengineering, GrassAttack*, GriefPrevention, GSit, InfinityExpansion, InteractionVisualizer, InteractiveChat, InteractiveChatDiscordSrvAddon, LightAPI, LuckPerms, MagicXpansion, Md5Lukas-Commons, Pl3xMap, PlaceholderAPI, ProtocolLib, SFCalc, SimpleEgg, SimpleMaterialGenerators, SimpleUtils, Slimefun, SlimefunOreChunks, SlimefunWarfare, SoulJars, spark, SurvivalInvisiframes, Vault, Waypoints

**Comment by Sytm** [comment]
Do you have by chance custom worlds? Like besides `world`, `world_nether` and `world_the_end`

**Comment by Apeiros-46B** [comment]
SlimefunWarfare adds `world_space` and DynaTech adds `dimensionalhome`.
There aren't any other custom worlds.
I had those two plugins before, but there weren't any issues other than the command sometimes failing to run but then working on the second execution.

**Comment by Apeiros-46B** [comment]
If this helps, `world_space` has a waypoint inside of it and players have gone to it
`dimensionalhome` does not have any waypoints and players have never been there

**Comment by Sytm** [comment]
Fixed/no longer valid for 3.0.0 because it now uses SQLite. If the issue still persits after updating write a comment here
