### ISSUE TITLE
No way of getting waypoint UUID

### ISSUE THREAD

**Issue by SynneyecXD** [Sytm/waypoints2#49]
I am unable to rename a waypoint from the GUI and I can't find a way of obtaining the UUID of a waypoint from a command. How can I rename or change the item of a waypoint?

I am playing on 1.17.

**Comment by Sytm** [comment]
Fixed in 3.0.0. 

Regarding getting UUIDs: Open a waypoint of your choice, have the permission `waypoints.command.scripting` and click on the item Get UUID
