### ISSUE TITLE
Dynmap integration?

### ISSUE THREAD

**Issue by gazpachoking** [Sytm/waypoints2#54]
Any chance dynmap integration could be added, such that waypoints showed up on dynmap if installed? I guess maybe just public ones would be appropriate.

**Comment by gazpachoking** [comment]
🤩 Awesome, thank you!

**Comment by gazpachoking** [comment]
Just peeked at the code a bit, am I right in thinking that removing the waypoint won't remove the dynmap marker ATM?

**Comment by Sytm** [comment]
Yeah, you are correct. The DynMap API was the most unpleasent API I had to use and wanted to just get over it.

But I have changed all that and also added the possiblity to change the Marker Set Icon and Marker Set Label in ba705cbcf3211fb48eb25e8a40d3be93e065495b

**Comment by gazpachoking** [comment]
Oh! Awesome! Thanks again! 🥇
