### ISSUE TITLE
[Feature request] Hologram support

### ISSUE THREAD

**Issue by NyaomiDEV** [Sytm/waypoints2#60]
**Is your feature request related to a problem? Please describe.**
Right now, waypoints' beacons disappear when the player gets too close in favor of a blinking block. I'd like if the plugin had a way of showing the beacon beam crossing the actual XYZ location, and to show a hologram at the exact location of the waypoint.

**Describe the solution you'd like**
Holograms support, to display waypoints in a more "traditional" fashion, inspired by minimap mods like Xaero's Minimap, VoxelMap and JourneyMap.

**Describe alternatives you've considered**
The blinking block is fancy but not fancy enough.

**Additional context**
There is none. I assume we all know how traditional waypoints' beams and holograms look like.

**Comment by Sytm** [comment]
But I still do not understand what you mean with
> I'd like if the plugin had a way of showing the beacon beam crossing the actual XYZ location

**Comment by NyaomiDEV** [comment]
> But I still do not understand what you mean
```
sky
 r|r <-- r is roof
  |
  x <-- actual location
  |
  |
ffOff <- beacon beam

f is floor
```

you could temporarily set all the blocks on top with air to make sure the beacon shows up; so, where to place the beacon? well, at the lowest air block starting from the waypoint location, minus one so it's level with the floor or w/e

the only problem is that the beacon should disappear if you're too close to it < B blocks in all X and Z directions, and for all Y values higher than the location of the beacon itself, with B being the value in the config
