### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by izaqqq** [Sytm/waypoints2#62]
I went to try to put the latest version and start the world and it gave this error I'll leave a photo 
![waypoints](https://user-images.githubusercontent.com/99193221/152805847-a12a4403-dddb-489c-afc2-59a2fe18725b.png)

**Comment by Sytm** [comment]
The latest version is 3.3.0, not 3.0.0.

The issue seems to be that you Java version is too old. Consider upgrading to Java 11

**Comment by izaqqq** [comment]
I used 3.3.0 but it wasn't and I changed it to 3.0.0 but I'll see what you said about java thank you <33

**Comment by izaqqq** [comment]
sorry for the delay I can't boot java 11 I think it's because I use windows 8.1 but thanks a lot for the help ;))
