### ISSUE TITLE
Error when clicking "Create new waypoint" in GUI

### ISSUE THREAD

**Issue by therbz** [Sytm/waypoints2#63]
When clicking "Create new waypoint" in the /waypoints GUI, the following null error is thrown and nothing happens client-side:
[https://hastebin.skyra.pw/vusuroberi.prolog](https://hastebin.skyra.pw/vusuroberi.prolog)

I'm using Java 17 with Paper 1.18.2 build #237, Waypoints 3.3.1.

**Comment by Sytm** [comment]
The error has been resolved with the latest release
