### ISSUE TITLE
GUI Menu Blocks can be duplicated

### ISSUE THREAD

**Issue by Parthodys** [Sytm/waypoints2#65]
For some reason, the Blocks such as Hopper, Ender Chest and Chest can be taken from the GUI menu if you quickly take one, close menu, then place down the block. This can lead to infinite Obsidian, Ender Chests, Chests, Hoppers, etc. We've had to disable the plugin until this can be fixed.
![2022-04-13_15 28 06](https://user-images.githubusercontent.com/1515422/163279071-0d0934c8-06e6-44f4-ae44-681e66d012e7.png)

We are running Waypoints 3.3.1, didnt see anything in further updates about this issue.

**Comment by Sytm** [comment]
Either your server is laggy and the player can "grab" the items, but are only client side, which upon interacting with a block they disappear or another plugin has a bad GUI implementation and interferes with mine.

[Working as intended](https://user-images.githubusercontent.com/21055143/163379319-12a263ac-a600-4fa5-b734-292fa415d006.mp4)

**Comment by Parthodys** [comment]
> Either your server is laggy and the player can "grab" the items, but are only client side, which upon interacting with a block they disappear or another plugin has a bad GUI implementation and interferes with mine.
> 
- Higher ping makes this much easier, yes. Plugin works ideally in a zero ping server.
- Essentially shift+click a block -> close inventory -> place block/switch action bar selection. The higher the ping, the more time you have to execute it properly.
- If you switch actionbar selection quickly rather than place the block, it sometimes lets you hold the block for as long as you want or until you place it. 
- If you place the block and mine it up quickly, it gives you the blocks, such as 8x Obsidian from an Ender Chest.
- We have several other GUI menu plugins which don't seem to have this issue.
- One potential, but unconfirmed interference could be MySQL Player Data Bridge, which is used to sync inventories across a network.

**Comment by Sytm** [comment]
I have tested it with a simulated ping of 1000ms and in creative mode I actually managed to break it, but in survival mode it seems to still work

https://user-images.githubusercontent.com/21055143/163568272-688759a6-be75-40da-a41a-d3ce21027877.mp4

https://user-images.githubusercontent.com/21055143/163568307-0314e71d-475c-4057-907d-025cd9e39ed2.mp4

**Comment by Parthodys** [comment]
Issue still persists even on newest version with very limited GUI menu.

We filled it with barriers and unobtainable items and some are still able to pull them out of the menu easily, but this time we can at least track them better.

Other GUI menu plugins do not have this issue, so this is definitely something wrong with the protection of Waypoints GUI.

It doesn't even seem to require lag, certain players are just able to get some of the blocks/items in the GUI menu and the items keep the menu names. I can't repeat the bug and neither can most of those who I asked, but it is definitely being abused by some players.

**Comment by maxfire2008** [comment]
This also happens for my server. There was a lag spike then I could dupe it. Yet to do further testing. Disregard for now - sorry

**Comment by Sytm** [comment]
If you are in survival mode and the item is actually server side and not a ghost/client side item and manage to somewhat consistently reproduce it, I'll look at it again.

**Comment by Parthodys** [comment]
We managed to get a player to repeat it before. They basically logged in, opened the Waypoints, pulled items into inventory while turning on airplane mode which makes their connection hang, then disabling airplane mode before server kicks you out, and it let them keep the item. Essentially taking the items while connection is hanging.

Even without such tricks, we constantly have some players pulling out the Waypoint menu blocks, even by accident. There definitely seems to be something that allows some to take the blocks, dont know if its ping, different client version or what, but it definitely happens. It only seemed to work on placeable blocks specifically, items which cannot be placed weren't pulled out afaik.

Issue doesn't exist with any of our other GUI menu plugins, even older ones. It would definitely be nice to get it fixed so that we don't have to fill the menu with unobtainable blocks, which are then blocked via WorldGuard.
