### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by kimi172** [Sytm/waypoints2#66]
I have the plugin on my server. It works for me, but my friends can’t use the public waypoints. How can I fix that?

**Comment by maxfire2008** [comment]
Have you given them the permission `waypoints.teleport.public` they will also need `waypoints.command.use`

**Comment by kimi172** [comment]
What command do I use to do this?

**Comment by maxfire2008** [comment]
You will need a permissions plugin such as [Luckperms](https://luckperms.net/wiki/Usage).

**Comment by kimi172** [comment]
I guess I already have it. Also das Luckperms plugin. But I'm pretty stupid

**Comment by Sytm** [comment]
If you haven't changed any permissions manually everything should work out of the box. Did you use the public waypoints (which can be seen by anyone at any time) or permissions waypoints (which can only be seen by people who also have the permission which is set at creation).

They could also have hidden the public waypoints by clicking on the chest/enderchest in the GUI.

---
Or if you meant by "can't use" they cannot teleport to them (if that is what you want), maxfire is correct and they additionally need `waypoints.teleport.public`
