### ISSUE TITLE
No limit to manual waypoint creation

### ISSUE THREAD

**Issue by ad-oliviero** [Sytm/waypoints2#73]
When adding a custom waypoint (shift + left-click on `create waypoint`), there should be a limit for the coordinates that can be set:
- max ±29999999 for the x and z coords
- min -63 (1.18) or 1 (1.17-) for the y coord
- max 319 (1.18) or 255 (1.17-) for the y coord

Why?

Because it can crash servers (based on a real experience).

**Comment by Sytm** [comment]
Entering the values themselves does nothing. Only teleporting to them makes the server crash. Gonna add limits anyway.
