### ISSUE TITLE
Ability to disable Connected Worlds

### ISSUE THREAD

**Issue by Deu07** [Sytm/waypoints2#74]
Please add possibility to disable Connected Worlds so that only waypoints from overworld are shown in overworld, and only from nether in nether.

**Comment by Sytm** [comment]
You can just remove the [entry](https://github.com/Sytm/waypoints/blob/c70b88dea1a00088301fb746598fae890be81e2b/waypoints/src/main/resources/config.yml#L37) for the connection between the Overworld and the Nether and it will stop doing that.
