### ISSUE TITLE
How to set Permissions in the pluggin?

### ISSUE THREAD

**Issue by Treidon** [Sytm/waypoints2#77]
How can I use waypoints.teleport.public in the configuration?

**Comment by Sytm** [comment]
What do you want do?

If you want to allow players to to teleport to public waypoints you must give your players with a permission plugin the given permission.

But what do mean with "in the configuration"?

**Comment by githubplanetarparrot** [comment]
If I understand your question, you would need to you a plugin permission manager like [LuckPerms](luckperms.net) and enable your player group to use the waypoints.teleport.public command.

**Comment by Sytm** [comment]
Yeah, I think with that answer this issue is resolved.
