### ISSUE TITLE
Add Oraxen support for inventory items or option to set custom_model_data for the item.

### ISSUE THREAD

**Issue by BiallyDEV** [Sytm/waypoints2#81]
It will give a option to make such a nice custom gui for compass as well as setting custom items as a compas.

**Comment by Sytm** [comment]
After thinking about this, how the API of Oraxen has to be used, the fact that I don't have models or similar to test these changes with and that Oraxen has to be paid for if a normal person wants to use it, I decided that I do not want to add this
