### ISSUE TITLE
Beacon issues :(

### ISSUE THREAD

**Issue by JonahTheEngi1** [Sytm/waypoints2#85]
Could you possibly add a option in the config to make the beacon and its glass unbreakable from both explosions and players, i want to use this on a server for factions but whilst testing I love everything other than the fact that the beacon beam greatly compromises bases if a waypoint is set on it which makes this an unusable plugin for my use case, i would really love the chance to use this plugin and great work everything else I have experienced with this plugin is fantastic.

**Comment by Sytm** [comment]
The beacon the plugin generates should only be visible to the player who selected the waypoint. Destruction caused by other players shouldn't affect the beacon either
