### ISSUE TITLE
Configure Item stacking in gui

### ISSUE THREAD

**Issue by TheGoofBall64** [Sytm/waypoints2#86]
So theres a very specific problem i have where when I open the GUI I cant use items that are stacked over 1 in the GUI without quick taking (shift click). BUT if I do so the GUI quickly selects everything that would be in subsequent menus later on. 

For example, my public waypoints folder stacks to 4 as of now (because I have 4 waypoints in it), I quick take (SHIFT click), it selects the folder then selects my spawn waypoint which is in the same inventory space in the next menu. I then have to select the back option. It gets quite annoying to have to do this. I think it had something to do with my other plugins I have installed or something idk

What I'm suggesting gets done about this is to add an option in the config where you can choose to not stack items in the GUI. That way if necessary, this can be changed by the person depending on your needs at the time.

ANOTHER REQUEST

Add commands for waypoints as well. such as commands that open each different GUI menu. and commands that can select and track your saved waypoints. Mainly what I mean is give the end user commands that allow you to use the mod with or without the GUI

If possible make it so you can require admins to also pay levels to teleport (currently I cannot find any way to do this). To explain this better, what I mean by this is that I want the option to also have admins be treated the same way as normal players with the waypoints. And idk lets say unless they are in creative mode it doesn't matter if the player is an op, admin, or anything. The same rules that apply to normal players also apply to oped players

**Comment by TheGoofBall64** [comment]
Oh and uhh, something else, the gui seems to be a little buggy too. sometimes it doesn't work at all and instead of opening the next menu when you select an item it takes it instead. I don't believe this to be a server problem as I have 3 other mods each with their own different gui's and that don't have this problem

**Comment by Sytm** [comment]
> So theres a very specific problem i have where when I open the GUI I cant use items that are stacked over 1 in the GUI without quick taking (shift click).

> Oh and uhh, something else, the gui seems to be a little buggy too. sometimes it doesn't work at all and instead of opening the next menu when you select an item it takes it instead. I don't believe this to be a server problem as I have 3 other mods each with their own different gui's and that don't have this problem

Could you pleaae tell me what these other plugins are, because in my testing without other (potentially interfering) plugins it works without issues.


----
> If possible make it so you can require admins to also pay levels to teleport (currently I cannot find any way to do this). To explain this better, what I mean by this is that I want the option

This can be done by revoking the permissions of the admins with an advanced permissions plugin. Specifically set the permission `waypoints.teleport.*` to false with LuckPerms for example.


---
> Add commands for waypoints as well. such as commands that open each different GUI menu. and commands that can select and track your saved waypoints. Mainly what I mean is give the end user commands that allow you to use the mod with or without the GUI

Please create an additional Issue with more details about the feature, because I don't properly understand what you mean with this

**Comment by Sytm** [comment]
Could you please test the GUI issues with this installed and please look into the Console output if Waypoints prints error messages?
[plugin.zip](https://github.com/Sytm/waypoints/files/10831661/plugin.zip) (had to put it in a zip because I cant upload jars here)

**Comment by TheGoofBall64** [comment]
> Could you pleaae tell me what these other plugins are, because in my testing without other (potentially interfering) plugins it works without issues.


Sorry for not answering sooner. I updated my server between then and now, but my plugins list is still the same 

```
CommandToItem
|CommandPanels
|Placeholder_API
|ViaVersion
Better_Structures
|Chunky
|Elite_Mobs
|Essentialsx
|Essentialsx_Spawn
|FastAsyncWorldEdit
|Geyser_[Floodgate]
Holographic_Displays
|PlugManX
|Libs_Disguises
|Vault
|WorldGaurd
|ExpensiveDeath
simplepets
backpacks remastered
graves
mcmmo
```

I was using commands to items, binding a compass to open /wp on right click

Originally, On both java and bedrock, if I used the plugins GUI bind of sneak clicking, the menu would open but it wouldn't work, it would act as a chest, I could just take the items out of the GUI and they would stay in my inventory instead of doing anything. Typing in the /wp command or using cti on the compass world work, however.

To sum that up, the majority of the time on bedrock, typing in the command /wp on bedrock produced a working GUI while shift-clicking a compass would almost never work.

- Also, on java stacked items in the GUI work fine (such as folders), except for a few random times and I just restarted the server and it fixed itself. But in bedrock you cannot open stacked items in this plugins GUI without quick taking. After quick taking, like opening a folder, it opens the folder, then opens any waypoint that would be in the same inventory slot in the next menu in quick succession. E.g. I open the public waypoints folder, it opens the spawn waypoint inside of the folder instead


Now, java works flawlessly except for a few tiny things. When making multiple saved public waypoints, once you get to 10 saved the 9th item gets duped in the menu (see image, the axes are the exact same waypoint, if I delete one both get deleted). but in Bedrock, if the GUI is opened by sneak clicking a compass it bugs out still, same thing happens with item stacking.

![image](https://user-images.githubusercontent.com/75709265/221752394-92c1245a-1a29-464b-a8e2-61177dc420e3.png)

Sorry if this sets you off at all but so far out of the 5 plugins that have gui's, yours is the only one with problems on bedrock (and occasionally java, requiring a restart). Its an awesome plugin though, one of my most used ones too.



Oh and the new jar didn't seem to do anything, it actually seemed to make stacked items disappear on some occasions needing to rejoin the server
- edit: Nevermind, stacked items perminently disappear after initially going away

**Comment by TheGoofBall64** [comment]
And id like to add that this problem I noticed around the time I only had these plugins on the server. But I didn't report it until like a week later so I ended up with more plugins.

Essentialsx
|Essentialsx_Spawn
Geyser_[Floodgate]
waypoints
simplepets
backpacks remastered
graves
mcmmo


Baised on what I know id say that this would happen if waypoints and geyser were put together, I think that kinda goes without being said but I'm pointing it out anyways for details sake. That being said Its also kinda odd that of all things, out of my 25 plugins or so, the only thing that doesn't work is your GUI specifically. everything else works, beacons, huds, overlays, and the top of the screen compass thing, everything.
- Like fricking elite mobs and its magic abilities and custom worlds with textured gui's and everything works flawlessly on both java and bedrock. That part surprises me, geyser impresses me






I know this issue might not take full priority, and I would understand given the circumstances. But if the main answer is no to this, could i suggest adding a little option in the config to disable item stacking in the GUI. I know it would be kinda like a quick and dirty fix, but your plugin is from my findings the best I could find that even has a GUI. And on top of that it seems like the best overall. It would be nice to have the option to disable item stacking

**Comment by Sytm** [comment]
I interpret your answer the following way:
- Items cannot be taken out and kept on Java
- The GUI function breaks only sometimes on Java an is fixed with a restart. Could you please go into more detail for that?
- But it breaks horribly when used with Bedrock-Crossplay via Gyser?

I can look into the Geyser stuff, but I am going to say that I wont provide full Bedrock support, because this is a Java Edition Plugin. Maybe I'll add a switch to disable Item-Stacking if the fix isn't as easy or even obvious.

**Comment by TheGoofBall64** [comment]
> The GUI function breaks only sometimes on Java an is fixed with a restart. Could you please go into more detail for that?

Every once in a while, I think its happened 2 or 3 times in the last 2 weeks. Although I've been making lots of changes and restarts to the server several times so it probably happened more often than usual because of how Im doing things but anyways. The GUI would bug and id be able to take out and keep items from the GUI on java. Prompting a server restart (maybe id just have to rejoin but I don't remember)


> Items cannot be taken out and kept on Java

Yes, the GUI works on java besides those few random times


> But it breaks horribly when used with Bedrock-Crossplay via Gyser?

Yes


> I can look into the Geyser stuff, but I am going to say that I wont provide full Bedrock support, because this is a Java Edition Plugin. Maybe I'll add a switch to disable Item-Stacking if the fix isn't as easy or even obvious.

Yeah that would make sense, maybe changing the shift click compass input to input /wp as the player? Im not sure how the shift click currently works for the compass, but normal right clicking a compass (or really any item, I used dirt to test) that's binded to the /wp command makes a working GUI (besides stacked items). While using your compass shortcut with shift clicking doesnt

**Comment by Sytm** [comment]
> Every once in a while, I think its happened 2 or 3 times in the last 2 weeks. Although I've been making lots of changes and restarts to the server several times so it probably happened more often than usual because of how Im doing things but anyways. The GUI would bug and id be able to take out and keep items from the GUI on java. Prompting a server restart (maybe id just have to rejoin but I don't remember)

If it is that rare, and you were messing with the server (restarts are fine, but reloading can break things) I can't do anything on that end.

> Yeah that would make sense, maybe changing the shift click compass input to input /wp as the player? Im not sure how the shift click currently works for the compass, but normal right clicking a compass (or really any item, I used dirt to test) that's binded to the /wp command makes a working GUI (besides stacked items). While using your compass shortcut with shift clicking doesnt

It seems like that geyser and/or bedrock don't like it if the inventory is opened on the same tick as the interact happened.
Adding a delay should fix that issue.

**Comment by TheGoofBall64** [comment]
> It seems like that geyser and/or bedrock don't like it if the inventory is opened on the same tick as the interact happened.
Adding a delay should fix that issue.

Ok thanks. Actually now that you point that out, in the past I used to only have a console version of Minecraft and I did a LOT of redstone and technical stuff, really pushed what the game would let me do. Bedrock edition has serious problems with several actions during the same tick (on the same item or system, block, etc). I found a way to consistently corrupt entire worlds by activating two pistons into each other many times per tick on bedrock where in java it works no problem. Long story short bedrock has quick tick issues, or however you would call it.

Anything on the item stacking yet?

**Comment by Sytm** [comment]
I have added a (possible) workaround for the compass open thing and the option to disable stack sizes.

I couldn't even connect to my local test server via Geyser and cannot diagnose the real issue nor verify that these fixes are working. Also additional Bedrock issues most likely won't be fixed because that is outside the scope of this plugin.

If you encounter any issues with a Java Edition client I will look at them if you open a new Github issue
