### ISSUE TITLE
Request: Distance, in blocks (meters), from a particular waypoint, in the hologram

### ISSUE THREAD

**Issue by NyaomiDEV** [Sytm/waypoints2#87]
Hello there!

It would be cool to have a feature where you update the hologram whenever the player gets closer or further away, so that it includes the distance between the player and the waypoint, measured in blocks.

Of course, this is something inspired from JourneyMap.

Also, a minor bug, but probably it's better to put the hologram in front of the beacon beam (I guess this is achievable by getting the block facing most close to the player and updating the X and Z coordinates to be X.000 - X.999 and Z.000 and Z.999)

This is an example (what happens now vs what I would like to happen (JourneyMap))
![image](https://user-images.githubusercontent.com/13177694/221415649-4d5e6152-aa18-482c-a774-6a5e4fcf5ea3.png)

**Comment by Sytm** [comment]
Displaying the distance and moving the armorstand closer to the player shouldn't be any problem.

The problem I currently see is that, well the name of the armorstand gets smaller the further you move away, which makes it not very useful for anything further away. Any suggestions for that?

**Comment by NyaomiDEV** [comment]
If you're really into geometry problems, you can make the armorstand so that it is facing the player, placed in a way that is X blocks away from the player at all times.

I am trying to oversimplify here but:

![image](https://user-images.githubusercontent.com/13177694/221419699-c00962f0-fe25-400c-820d-2c21c530570a.png)

![image](https://user-images.githubusercontent.com/13177694/221419828-32486088-1061-44b7-a70f-d87f6b549034.png)

Pardon my shitty mouse drawing skills.

You can get (x, z) for the armorstand by using vector arithmetic, or you can go the linear algebra route too.

(arguably this could solve a lot of problems with blocks getting in the way and obscuring the view for every distance D > K, which you could just avoid by making K = min(K, distance from first obscuring block))

**Comment by NyaomiDEV** [comment]
well, this ended up being a linear algebra problem, lol
@Sytm you still there?

**Comment by Sytm** [comment]
Yeah yeah, I am still here. I had something like this in mind, but I kinda don't want to program all that :c.

Well looks like I'll have a look into it and do it. How soon™ depends on if there is any energy left after work next week.

**Comment by NyaomiDEV** [comment]
Well, I had a moment to get into research.

Turns out that the distance in 3d space equation is dead simple, and it shouldn't be a problem to implement with a task that updates the hologram every second or so, as not to lag the server much.

The problems come afterwards, that is because you noticed that the hologram is fixed and being occluded by stuff.

By going with the distance Dconfig route, you need to get the 3d line equation between the player's head position and the waypoint hologram's target position; you then shall treat all potentially line-intersecting blocks' faces facing the player as 3d planes, and check for intersection so that you can derive the position of the point of intersection between the line and the occluding plane. Once you have that position, you can again calculate a 3d distance and call it Dmax, and then you can basically set Darmorstand as min(Dconfig, Dmax) and then solve for a point of distance Darmorstand on the line for which you already have the equation.

It is a ton of work and I feel you should do it only if you are a perfectionist.

**Comment by Sytm** [comment]
> The problems come afterwards, that is because you noticed that the hologram is fixed and being occluded by stuff.

I think I'll actually do it this way, because otherwise the hologram could get very "jumpy", depending on the conditions of course. And I think that should do the trick, because this is a server-side only replacement/imitation for Waypoint mods, not a mod.

> By going with the distance Dconfig route, you need to get the 3d line equation between the player's head position and the waypoint hologram's target position; you then shall treat all potentially line-intersecting blocks' faces facing the player as 3d planes, and check for intersection so that you can derive the position of the point of intersection between the line and the occluding plane. 

FYI: There is this handy Method: [World.rayTrace](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#rayTraceBlocks(org.bukkit.Location,org.bukkit.util.Vector,double)) ;) (If you ever should interact with the Spigot API, I dunno if you make plugins)

> It is a ton of work and I feel you should do it only if you are a perfectionist.

Luckily I can toggle my perfectionism on demand

**Comment by NyaomiDEV** [comment]
> I dunno if you make plugins

I did, but those were for Minecraft Pocket Edition servers. Still, those APIs are really heavily inspired by the Bukkit API so I am almost certain I could manage in the Java space, if need be.

I'd really like to make something, some day, though!

**Comment by Sytm** [comment]
I'll try to address the other current issue and then I'll create a new release

**Comment by Sytm** [comment]
Hi, if you want to try the holograms out ahead of time you can download the jar from [here](https://github.com/Sytm/waypoints/actions/runs/4307334802) from the artifacts section
