### ISSUE TITLE
Custom icon per waypoint -- but as an item display below the hologram!

### ISSUE THREAD

**Issue by NyaomiDEV** [Sytm/waypoints2#88]
Yes, I came up with another one of my silly ideas for this plugin. At this rate I better learn Kotlin myself and come up with PRs.

BUT ANYWAY!

The idea is that since you can define a custom item to use as icon, then you can also make that item or block rotate below the waypoint hologram pointer!

Also, this way you can spawn a named item and not necessarily an armorstand; but I don't know personally if there are caveats to not using armorstands for floating text.

**Comment by Sytm** [comment]
> The idea is that since you can define a custom item to use as icon, then you can also make that item or block rotate below the waypoint hologram pointer!

So you mean like the item is floating below the hologram text?

**Comment by NyaomiDEV** [comment]
> So you mean like the item is floating below the hologram text?

Exactly!

**Comment by Sytm** [comment]
Ok, I'll try to see what I can come up with.

It's either going to be a rotating item or one held in the hand of another armorstand

**Comment by Sytm** [comment]
My first draft of the item, but at the moment it is _very_  jittery, even if you crank the update interval up to 1 tick.

I'll see if I can do some trickery to make it work smoother

**Comment by NyaomiDEV** [comment]
Probably you could just name the item instead of using the armorstand.
Also, this means that you can flag the entity so that the item name shows only when you look at it with the crosshair (another thing mods have).

**Comment by Sytm** [comment]
> Probably you could just name the item instead of using the armorstand.

Can be done, but the item can clip into the text, which kinda looks meh. Now its two hidden armor stands and the item

> Also, this means that you can flag the entity so that the item name shows only when you look at it with the crosshair (another thing mods have).

I have tested that and non-standard mobs (even the armor stand) can only have the name tag always visible or never, unlike sheep for example, that will show the name tag if you look at it like you mentioned

**Comment by NyaomiDEV** [comment]
> I have tested that and non-standard mobs (even the armor stand) can only have the name tag always visible or never, unlike sheep for example, that will show the name tag if you look at it like you mentioned

Pain
