### ISSUE TITLE
[Request] Select multiple waypoints

### ISSUE THREAD

**Issue by NyaomiDEV** [Sytm/waypoints2#92]
In a regular client mod scenario, this happens (notice on/off switches):

![image](https://user-images.githubusercontent.com/13177694/226172124-9f965a32-d31c-45bb-ae84-51a3f65cb152.png)

What then happens is that beacons/holograms/icons for the enabled waypoints are visible in the world.
To make this plugin behave more like a mod, it would only make sense if you can "enable" or "select" multiple waypoints at once.

This will probably look ugly for the particle indicator, so for that reason just... keep that off just in case?

Oh and also you would probably want to keep the waypoints selected between player sessions? But for the love of God use another database file for that if you decide to do that.

**Comment by Sytm** [comment]
Might do.

Selected Waypoints are already saved between sessions ;)

(Or atleast _should_)
