### ISSUE TITLE
Use DisplayEntities instead of ArmorStands for hologram pointer

### ISSUE THREAD

**Issue by NyaomiDEV** [Sytm/waypoints2#93]
This is more of a forward-looking writeup as it doesn't outline a bug nor a feature request.

The main idea is that since 1.19.4 there's the Display entity which can be used to avoid armor stands. You might not want to use it for items, even though it can display them, because it cannot display block entities (so people can't use chests for items - and spinny thing is always better than static thing); but one less armor stand per hologram! And you get to color the text background and modify its scale.

Though I don't see ProtocolLib merging 1.19.4 changes just yet; that's why I was saying this is more of a forward-looking writeup.

Stuff you might be interested in: https://minecraft.fandom.com/wiki/Display

**Comment by Sytm** [comment]
Looks in fact somewhat interesting. In case I want to torture myself a little bit more with the MC Protocol I'll see what can be done
