### ISSUE TITLE
Stopped working when updated to 1.20.1

### ISSUE THREAD

**Issue by MRMAXTHEMAC** [Sytm/waypoints2#99]
**Describe the bug**
Waypoints not starting after I updated to 1.20.1

**To Reproduce**
Try to start the server, shows error log and "is your server up to date" error message (see screenshot)

**Expected behavior**
the plugin to work like it did on 1.20

**Screenshots**
![image](https://github.com/Sytm/waypoints/assets/136647132/bcedd71e-c02c-4766-a5e9-b9f6893c0673)

**Additional context**

- [x] I am using the latest version of Waypoints available

**Comment by Sytm** [comment]
You are running v3.6.4. v3.6.5 has been released today to add support for 1.20.1

**Comment by MRMAXTHEMAC** [comment]
3.6.5 is not uploaded on Hangar. Clicking dowload on the blue icon here https://hangar.papermc.io/md5lukas/Waypoints takes me to https://modrinth.com/plugin/waypoints/version/3.6.4

**Comment by Sytm** [comment]
https://modrinth.com/plugin/waypoints/version/3.6.5
